---
- name: Apply updates to all managed nodes
  hosts: all
  become: true
  roles:
    - common

- name: Install and configure Prometheus on Ubuntu servers
  hosts: ubuntu_servers
  become: true
  roles:
    - prometheus_ubuntu

- name: Install and configure Prometheus on CentOS servers
  hosts: centos_servers
  become: true
  roles:
    - prometheus_centos

