---
- name: install Nagios Core on CentOS
  hosts: centos_servers
  become: true

  tasks:
    - name: Download and extract Nagios Core source
      ansible.builtin.unarchive:
        src: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.5.1.tar.gz
        dest: /tmp
        remote_src: true
        creates: /tmp/nagios-4.5.1
      when: ansible_distribution == "CentOS"
