---
- name: Apply updates to all managed nodes
  hosts: all
  become: true
  roles:
    - common

- name: Install and configure Nagios on Ubuntu servers
  hosts: ubuntu_servers
  become: true
  roles:
    - nagios_ubuntu

- name: Install and configure Nagios on CentOS servers
  hosts: centos_servers
  become: true
  roles:
    - nagios_centos
