---
- name: Create multiple files
  hosts: all
  tasks:
    - name: Create multiple files
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: touch
      loop:
        - file1.txt
        - file2.txt
        - file3.txt

