---
# tasks file for prometheus_centos
- name: create Prometheus system user
  ansible.builtin.user:
    name: prometheus
    shell: /bin/false
    system: true
    create_home: false
    state: present
  become: true

- name: create Prometheus group
  ansible.builtin.group:
    name: prometheus
    state: present

- name: create /etc/prometheus
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    mode: '0755'
    owner: prometheus
    group: prometheus

- name: create /var/lib/prometheus
  ansible.builtin.file:
    path: /var/lib/prometheus
    state: directory
    mode: '0755'
    owner: prometheus
    group: prometheus

- name: download and extract Prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v3.14.0/prometheus-3.14.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: true
    creates: /tmp/prometheus-3.14.0.linux-amd64.tar.gz

- name: copy Prometheus binaries to /usr/local/bin/

  ansible.builtin.copy:
    src: "{{  item.src  }}"
    dest: "{{  item.dest  }}"
    remote_src: true
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - { src: '/tmp/prometheus-3.14.0.linux-amd64/prometheus', dest: '/usr/local/bin/prometheus' }
    - { src: '/tmp/prometheus-3.14.0.linux-amd64/promtool', dest: '/usr/local/bin/promtool' }

- name: copy Prometheus yaml file to /etc/prometheus/
  ansible.builtin.copy:
    src: '/tmp/prometheus-3.14.0.linux-amd64/prometheus.yml'
    dest:  '/etc/prometheus/prometheus.yml'
    remote_src: true
    owner: prometheus
    group: prometheus

- name: Prometheus config file verification
  ansible.builtin.command: /usr/local/bin/promtool check config /etc/prometheus/prometheus.yml
  register: promtool_check
  changed_when: false
  failed_when: promtool_check.rc != 0

- name: create Prometheus systemd service file
  ansible.builtin.copy:
    src: ~/CPE212_loterte/midterm_skills/prometheus.service
    dest: /etc/systemd/system/prometheus.service
    owner: prometheus
    group: prometheus


- name: Start and enable Prometheus service
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: true
    daemon_reload: true
  become: true



